### ISSUE TITLE
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'? error

### ISSUE THREAD

**Issue by MachineGalaxy** [skier233/nsfw_ai_model_server#22]
I'm having an issue with the Stash plugin. Specifically after I updated to V2.
When I try and tag anything the command fails and the error in the console is "ModuleNotFoundError: No module named 'cv2'" after some deeper digging it also says "Exception: Failed to install opencv-python".

When I try and install opencv-python manually I get the error "AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?"

I've been trying to figure out the root cause and a fix but I've only had very limited time to play around with it and haven't found a fix as of yet.

**Comment by skier233** [comment]
Can you try updating the stash plugin to the latest version? I put out a fix for users having this issue when running stash inside a docker container.

**Comment by MachineGalaxy** [comment]
I'm now getting some new errors

ModuleNotFoundError: No module named 'imageio'
ERROR: Failed building wheel for psutil
psutil could not be installed from sources because gcc is not installed

**Comment by skier233** [comment]
I'm assuming you're running stash in docker? If so, in your virtual environment you used for the stash dependencies run:
pip install imageio[ffmpeg]

**Comment by skier233** [comment]
Are you running that inside the docker container or in the virtualenv on the host computer used for stash?

**Comment by MachineGalaxy** [comment]
In the docker container

**Comment by skier233** [comment]
You'll want to install the pip dependencies in a virtualenv outside the docker container. Anything installed inside the docker container won't be saved due to docker's lifecycle. There's instructions here about creating the virtualenv: https://github.com/skier233/nsfw_ai_model_server/wiki/Stash-Plugin-Guide#docker-installation-for-when-running-stash-inside-docker
Also when executing those steps, after installing the requirements.txt, step 7, you'll want to run that command above:
`pip install imageio[ffmpeg]`

**Comment by MachineGalaxy** [comment]
Ahh ok. I'll need to look into it as im running unRaid and that doesn't have python or virtualenv by default. Once I get it working I'll let you know of the results

**Comment by MachineGalaxy** [comment]
Managed to get it to work. For some reason imageio refused to install automaticity when the plug-in ran so I had to install it manually. Might be an idea to add it to the requirements.txt to rule it out in the future from erroring out.

Thanks for the help again.

**Comment by skier233** [comment]
No worries. I added it to the requirements.txt last week: https://github.com/stashapp/CommunityScripts/commit/fd2f33bf01a67e0d7ea20febfa034506869c2c0f
